[build]
src = "src/"
output = "data/"

[template]
ore = ['coal_ore', 'lapis_ore', 'iron_ore', 'gold_ore', 'diamond_ore', 'emerald_ore', 'nether_gold_ore', 'redstone_ore', 'nether_quartz_ore', 'ancient_debris', 'copper_ore', 'deepslate_coal_ore', 'deepslate_iron_ore', 'deepslate_copper_ore', 'deepslate_redstone_ore', 'deepslate_emerald_ore', 'deepslate_lapis_ore', 'deepslate_diamond_ore']